name: packer

on:
  - push

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/builder.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer"
      
      - name: Packer build
        id: build
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
        run: "packer build -debug ./packer"
